version: "3.2"
services:
  app:
    build: .
    ports:
      - published: ${APP_PORT}
        target: 4000
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=4000
      - SECRET=${JWT_SECRET}
      - OMDB_API_KEY=${OMDB_API_KEY}
